print('Hello Tiltfile')

print('Installing dashboard')
k8s_yaml(['kubernetes-dashboard.yaml']) 

print('Creating dashboard user')
k8s_yaml(['dashboard-adminuser.yaml']) 

print('Deploying Goof')
k8s_yaml(['goof-namespace.yaml']) 
k8s_yaml(['goof-deployment.yaml']) 
k8s_yaml(['mongo-deployment.yaml']) 

print('Deploying Snyk')
k8s_yaml('snyk-monitor-namespace.yaml')
k8s_yaml('snyk-monitor-secret.yaml')
